// <auto-generated />
using System;
using BlazorMentorApp.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorMentorApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201008042235_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorMentorApp.Models.Mentors", b =>
                {
                    b.Property<int>("MentorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MentorsId");

                    b.HasIndex("QualificationId");

                    b.ToTable("mentors");

                    b.HasData(
                        new
                        {
                            MentorsId = 1,
                            Email = "johnWick@gmail.com",
                            FirstName = "john",
                            Gender = 0,
                            LastName = "wick",
                            PhotoPath = "images/car2.jpeg",
                            Username = "JW"
                        },
                        new
                        {
                            MentorsId = 2,
                            Email = "janeWick@gmail.com",
                            FirstName = "jane",
                            Gender = 1,
                            LastName = "wick",
                            PhotoPath = "images/car3.jpeg",
                            Username = "JW"
                        });
                });

            modelBuilder.Entity("BlazorMentorApp.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("QualificationId");

                    b.ToTable("Qualification");
                });

            modelBuilder.Entity("BlazorMentorApp.Models.Mentors", b =>
                {
                    b.HasOne("BlazorMentorApp.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId");
                });
#pragma warning restore 612, 618
        }
    }
}
